# Your preferred terminal emulator
set $term gnome-terminal

# Start a terminal
bindsym $mod+Return exec $term

# NetworkManager applet
exec nm-applet

# Translate select text
# https://github.com/fanhenrique/translate-select-text
bindsym $mod+b exec translate


# Screenshot of the focused output
bindsym --release $mod+p exec grimshot save output "$HOME/screenshot/$(date '+%Y-%m-%d_%H-%M-%S').png"

# Screenshot of the selected area
bindsym --release $mod+Shift+p exec grimshot save area "$HOME/screenshot/$(date '+%Y-%m-%d_%H-%M-%S').png"

# ============================================================
# Application workspaces
# ============================================================

# Zen Browser
for_window [app_id="app.zen_browser.zen"] move container to workspace 1

# VSCodium
for_window [app_id="com.vscodium.codium"] move container to workspace 2

# Pavucontrol
for_window [app_id="org.pulseaudio.pavucontrol"] move container to workspace 8

# Bitwarden
for_window [class="bitwarden"] move container to workspace 9

# Discord
for_window [app_id="discord"] move container to workspace 10

# Zenity
for_window [app_id="zenity"] floating enable


# ============================================================
# Application shortcuts
# ============================================================

bindsym $mod+Control+n exec flatpak run app.zen_browser.zen
bindsym $mod+Control+c exec flatpak run com.vscodium.codium
bindsym $mod+Control+p exec flatpak run org.pulseaudio.pavucontrol
bindsym $mod+Control+b exec flatpak run com.bitwarden.desktop
bindsym $mod+Control+d exec flatpak run com.discordapp.Discord


# ============================================================
# Wallpaper
# ============================================================

# swaybg installation required
# sudo apt install swaybg
exec swaybg -i "$HOME/wallpaper/debian-wallpaper.jpg" -m center