# Borders

# Default border style for new windows

# default_border normal|none|pixel
default_border pixel 5px

# default_floating_border normal|none|pixel
default_floating_border pixel 5px

# Hiding borders adjacent to the screen edges
# hide_edge_borders none|vertical|horizontal|both|smart|smart_no_gaps
hide_edge_borders none

# Gap between windows
# gaps inner <gap_size>[px]
# gaps inner 5px

# Gap around windows
# gaps outer|horizontal|vertical|top|left|bottom|right <gap_size>[px]
# gaps outer 5px