# # Workspace colors
set $border_color #2f343a
set $focused_color #c4c4c4
set $focused_text #000000
set $active_color #3a3a3a
set $active_text #d9d9d9
set $inactive_color #3a3a3a
set $inactive_text #d9d9d9
set $urgent_color #900000
set $urgent_text #d9d9d9
set $binding_color #900000
set $binding_text #d9d9d9

# Default colors
#
# <colorclass>            <border>   <background>   <text>    <indicator>   <child_border>
# client.focused          #4c7899      #285577      #ffffff     #2e9ef4      #285577
# client.focused_inactive #333333      #5f676a      #ffffff     #484e50      #5f676a
# client.unfocused        #333333      #222222      #888888     #292d2e      #222222
# client.urgent           #2f343a      #900000      #ffffff     #900000      #900000
# client.placeholder      #000000      #0c0c0c      #ffffff     #000000      #0c0c0c
# client.background       #ffffff


client.focused $focused_color $focused_color $focused_text $focused_color $focused_color
client.focused_inactive $inactive_color $inactive_color $inactive_text $inactive_color $inactive_color
client.unfocused $inactive_color $inactive_color $inactive_text $inactive_color $inactive_color