alias bat="batcat"
alias update="sudo apt update && sudo apt upgrade"
alias hg="history | grep"
alias mkdir="mkdir -pv"
alias ls="exa"
alias ..="cd .."
alias diff="diff --color='auto'"
alias xc="xclip -selection clipboard"
alias filesize="du -sh * | sort -h"
alias weather="curl https://wttr.in/"
