#!/bin/bash

source "$HOME/.config/i3blocks/scripts/utils/utils"
source "$HOME/.config/i3blocks/scripts/utils/expandable"

EXPANDABLE_FILE="$EXPANDABLE_DIR/cpu"

CPU_STATE_FILE="$EXPANDABLE_DIR/cpu-state"

SIGNAL=4

# toggle mode by clicking
case "$BLOCK_BUTTON" in
    1) expandable_start "$EXPANDABLE_FILE" "$SIGNAL" ;;
    3) expandable_toggle "$EXPANDABLE_FILE" ;;
esac

read -r cpu user nice system idle iowait irq softirq steal guest guest_nice < /proc/stat

total=$((user + nice + system + idle + iowait + irq + softirq + steal))
idle_total=$((idle + iowait))

usage="0.0"

if [[ -f "$CPU_STATE_FILE" ]]; then
    read -r last_total last_idle < "$CPU_STATE_FILE"

    dt=$((total - last_total))
    di=$((idle_total - last_idle))

    if (( dt > 0 )); then
        usage=$(awk -v dt="$dt" -v di="$di" \
            'BEGIN { printf "%.1f", ((dt - di) / dt) * 100 }')
    fi
fi

printf "%s %s\n" "$total" "$idle_total" > "$CPU_STATE_FILE"

if expandable "$EXPANDABLE_FILE"; then
    printf "<b>CPU</b> %s %4.1f%%\n" "$(ramp "$usage")" "$usage"
else
    printf "<b>CPU</b> %s\n" "$(ramp "$usage")"
fi