#!/bin/bash

source "$HOME/.config/i3blocks/scripts/utils/utils"
source "$HOME/.config/i3blocks/scripts/utils/expandable"

EXPANDABLE_FILE="$EXPANDABLE_DIR/filesystem"

SIGNAL=6

PARTITIONS=(
    "/"
    "/home"
)

get_fs_info() {
    df -hP "$1" 2>/dev/null | awk 'NR==2 {
        gsub("%","",$5)
        print $3, $2, $5
    }'
}

case "$BLOCK_BUTTON" in
    1) expandable_start "$EXPANDABLE_FILE" "$SIGNAL";;
    3) expandable_toggle "$EXPANDABLE_FILE";;
esac

output=""

for partition in "${PARTITIONS[@]}"; do
    read -r used size percent <<<"$(get_fs_info "$partition")"

    if expandable "$EXPANDABLE_FILE"; then
        output+="${output:+ }<b>$partition</b> $(ramp "$percent") $percent% ($used/$size)"
    else
        output+="${output:+ }<b>$partition</b> $(ramp "$percent")"
    fi
done

printf "%s\n" "$output"