#!/bin/bash

led=$(xset -q | awk '/LED mask:/ {print $NF}')

active=()

# Caps Lock
((led & 1)) && active+=("CAPS")

# Num Lock
(($led & 2)) && active+=("NUM")

# Se nenhum estiver ativo, não exibe o bloco
((${#active[@]} == 0)) && exit 0

text="${active[*]}"

printf "<span foreground='#00ff00' weight='bold'>%s</span>" "$text"
