#!/bin/bash

source "$HOME/.config/i3blocks/scripts/utils/utils"

STATE_FILE="/tmp/i3blocks-memory"

# toggle mode by clicking
if [[ "$BLOCK_BUTTON" == "1" ]]; then
    [[ -e "$STATE_FILE" ]] && rm "$STATE_FILE" || touch "$STATE_FILE"
    pkill -RTMIN+5 i3blocks >/dev/null 2>&1
fi

mem=$(free | awk '/Mem:/ {printf "%.0f", $3/$2*100}')
swap=$(free | awk '/Swap:/ {if ($2 > 0) printf "%.0f", $3/$2*100; else print 0}')


if [ -e "$STATE_FILE" ]; then
    printf "<b>RAM</b> %s <b>SWAP</b> %s\n" "$(ramp "$mem")" "$(ramp "$swap")"
else
    printf "<b>RAM</b> %s %s%% <b>SWAP</b> %s %s%%\n" \
        "$(ramp "$mem")" "$mem" \
        "$(ramp "$swap")" "$swap"
fi