#!/bin/bash

source "$HOME/.config/i3blocks/scripts/utils/expandable"

EXPANDABLE_FILE="$EXPANDABLE_DIR/network"

SIGNAL=7
CACHE="/dev/shm/network"

case "$BLOCK_BUTTON" in
    1) expandable_start "$EXPANDABLE_FILE" "$SIGNAL" ;;
    3) expandable_toggle "EXPANDABLE_FILE" ;;
esac

# Use the provided interface, otherwise the device used for the default route.
if [[ -n $BLOCK_INSTANCE ]]; then
  INTERFACE=$BLOCK_INSTANCE
else
  INTERFACE=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

OPERSTATE="/sys/class/net/$INTERFACE/operstate"

if [[ ! -r "$OPERSTATE" || $(<"$OPERSTATE") != up ]]; then
    printf "<span foreground='#61afef' weight='bold'>%s</span> <span foreground='#bf616a'>down</span>\n" "$INTERFACE"
    exit 0
fi

RX_FILE="/sys/class/net/$INTERFACE/statistics/rx_bytes"
TX_FILE="/sys/class/net/$INTERFACE/statistics/tx_bytes"

rx=$(<"$RX_FILE")
tx=$(<"$TX_FILE")
now=$(date +%s)

CACHE_FILE="${CACHE}-${INTERFACE}"

if [[ ! -f "$CACHE_FILE" ]]; then
    printf "%s %s %s\n" "$now" "$rx" "$tx" > "$CACHE_FILE"
    chmod 666 "$CACHE_FILE"
fi

read -r old_time old_rx old_tx < "$CACHE_FILE"

printf "%s %s %s\n" "$now" "$rx" "$tx" > "$CACHE_FILE"

dt=$((now - old_time))
((dt > 0)) || dt=1

rx_rate=$(((rx - old_rx) / dt))
tx_rate=$(((tx - old_tx) / dt))

format_rate() {
    # shift by 10 bytes to get KiB/s. If the value is larger than
    # 1024^2 = 1048576, then display MiB/s instead
    local rate=$1

    if ((rate >= 1048576)); then
        printf "%5.1f<b>M</b>" "$(awk "BEGIN {print $rate/1048576}")"
    elif ((rate >= 1024)); then
        printf "%5.1f<b>K</b>" "$(awk "BEGIN {print $rate/1024}")"
    else
        printf "%5.f<b>B</b>" "$(awk "BEGIN {print $rate}")"
    fi
}

if (expandable "$EXPANDABLE_FILE"); then

    IPADDR=$(ip -4 addr show "$INTERFACE" | awk '/inet / {print $2}' | cut -d/ -f1)

    printf "<span foreground='#00ff00' weight='bold'>%s</span> " "$INTERFACE"
    printf "<b>%s</b> " "$IPADDR"
    printf "<b>↓</b>%s " "$(format_rate "$rx_rate")"
    printf "<b>↑</b>%s\n" "$(format_rate "$tx_rate")"
else
    printf "<span foreground='#00ff00' weight='bold'>%s</span>\n" "$INTERFACE"
fi