# Terminal
bindsym $mod+Return exec i3-sensible-terminal

#  Translate select text 
# https://github.com/fanhenrique/translate-select-text
bindsym $mod+b exec --no-startup-id translate

# Brightness monitors
# https://github.com/fanhenrique/monitorctl
bindsym $mod+comma exec --no-startup-id brightness --down --step 0.1 --monitor $monitors
bindsym $mod+period exec --no-startup-id brightness --up --step 0.1 --monitor $monitors
bindsym $mod+m exec --no-startup-id brightness --reset --monitor $monitors

# Red shift monitors
# redshift installation required
# sudo apt install redshift
bindsym $mod+slash exec --no-startup-id redshift -O 5500 -m randr

# Screenshot of the window in focus
bindsym --release $mod+p exec --no-startup-id scrot --focused "$HOME/screenshot/%Y-%m-%d_%H-%M-%S.png"
# Screenshot of the cropping area
bindsym --release $mod+Shift+p exec scrot --select "$HOME/screenshot/%Y-%m-%d_%H-%M-%S.png"

# Shortcuts to open applications
bindsym $mod+Control+f exec firefox
bindsym $mod+Control+b exec flatpak run com.bitwarden.desktop
bindsym $mod+Control+d exec flatpak run com.discordapp.Discord
bindsym $mod+Control+c exec codium
bindsym $mod+Control+p exec pavucontrol

# Wallpaper
# feh installation required
# sudo apt install feh
exec --no-startup-id feh --bg-center ~/debian-wallpaper.jpg