# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# Terminal
bindsym $mod+Return exec i3-sensible-terminal

#  Translate select text 
# https://github.com/fanhenrique/translate-select-text
bindsym $mod+b exec --no-startup-id translate

# Brightness monitors
# https://github.com/fanhenrique/monitorctl
bindsym $mod+comma exec --no-startup-id brightness --down --step 0.1 --monitor $monitors
bindsym $mod+period exec --no-startup-id brightness --up --step 0.1 --monitor $monitors
bindsym $mod+m exec --no-startup-id brightness --reset --monitor $monitors

# Red shift monitors
# redshift installation required
# sudo apt install redshift
bindsym $mod+slash exec --no-startup-id redshift -O 5500 -m randr

# Screenshot of the window in focus
bindsym --release $mod+p exec --no-startup-id scrot --focused "$HOME/screenshot/%Y-%m-%d_%H-%M-%S.png"
# Screenshot of the cropping area
bindsym --release $mod+Shift+p exec scrot --select "$HOME/screenshot/%Y-%m-%d_%H-%M-%S.png"

# Flatpak application workspaces
for_window [class="^zen$"] move container to workspace 1
for_window [class="com.vscodium.codium"] move container to workspace 2
for_window [class="pavucontrol"] move container to workspace 8
for_window [class="bitwarden"] move container to workspace 9
for_window [class="discord"] move container to workspace 10

# Shortcuts to open Flatpack applications
bindsym $mod+Control+n exec --no-startup-id flatpak run app.zen_browser.zen
bindsym $mod+Control+c exec --no-startup-id flatpak run com.vscodium.codium
bindsym $mod+Control+p exec --no-startup-id flatpak run org.pulseaudio.pavucontrol
bindsym $mod+Control+b exec --no-startup-id flatpak run com.bitwarden.desktop
bindsym $mod+Control+d exec --no-startup-id flatpak run com.discordapp.Discord

# Wallpaper
# feh installation required
# sudo apt install feh
exec --no-startup-id feh --bg-center ~/wallpaper/debian-wallpaper.jpg
