### bar.conf

include ~/.config/i3/colors.conf

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {

    # Default bar
    # status_command i3status
		
    # i3blocks installation required
    # sudo apt install i3blocks
	status_command i3blocks

    # Font bar
	font pango:DejaVu Sans Mono 12
	
    # Show workspace number in bar
    workspace_buttons yes

    # Show bar to one or more monitors
    # output primary|nonprimary|<output>
    # output primary

    # Show icons in bar on monitor
    # tray_output none|primary|<output>
	tray_output primary

	# mode dock|hide|invisible
	mode dock

	# hidden_state hide|show
	hidden_state show

	# modifier <Modifier>|none
	modifier none

    # position top|bottom
	position top


    ################
    ## Colors bar ##
    ################
	# Default color
	# colors {
    #     background #000000
    #     statusline #ffffff
    #     separator #666666
    
    #     <colorclass>       <border>   <background>   <text>
    #     focused_workspace  #4c7899      #285577      #ffffff
    #     active_workspace   #333333      #5f676a      #ffffff
    #     inactive_workspace #333333      #222222      #888888
    #     urgent_workspace   #2f343a      #900000      #ffffff
    #     binding_mode       #2f343a      #900000      #ffffff
    # }

	colors {
	    background #000000
		statusline #C9D6DF
        separator #666666
		
        focused_workspace  $focused_color $focused_color $focused_text_color
		active_workspace   $focused_inactive_color $focused_inactive_color $focused_inactive_text_color
		inactive_workspace $focused_inactive_color $focused_inactive_color $focused_inactive_text_color
		urgent_workspace   #2f343a #900000 #ffffff
		binding_mode       #2f343a #900000 #ffffff
	}
}

