bar {
    status_command i3blocks
    font pango:DejaVu Sans Mono 12

    workspace_buttons yes
    tray_output primary

    mode dock
    hidden_state show
    modifier none
    position top

    colors {
        background $bg
        statusline $fg
        separator $separator

        focused_workspace \
            $border_color \
            $focused_color \
            $focused_text

        active_workspace \
            $border_color \
            $active_color \
            $active_text

        inactive_workspace \
            $border_color \
            $inactive_color \
            $inactive_text

        urgent_workspace \
            $border_color \
            $urgent_color \
            $urgent_text

        binding_mode \
            $binding_color \
            $binding_color \
            $urgent_text
    }
}