# Borders
# default_border normal|none|pixel
# default_border normal|pixel <px>
default_border pixel 5px
default_floating_border pixel 5px

# hide_edge_borders none|vertical|horizontal|both|smart|smart_no_gaps
hide_edge_borders none

# Gap between windows
# gaps inner 5px
# Gap around windows
# gaps outer 5px
