### colors.conf

set $focused_color #c4c4c4
set $focused_text_color #000000
set $focused_inactive_text_color #d9d9d9
set $focused_inactive_color #3a3a3a


client.focused		    $focused_color          $focused_color          $focused_text_color          $focused_color
client.focused_inactive $focused_inactive_color $focused_inactive_color $focused_inactive_text_color $focused_inactive_color
client.unfocused        $focused_inactive_color $focused_inactive_color $focused_inactive_text_color $focused_inactive_color