# Use pactl to adjust volume in PulseAudio.
# Volume control
set $refresh_volume pkill -RTMIN+10 i3blocks
bindsym $mod+XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5% && $refresh_volume
bindsym $mod+XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5% && $refresh_volume
bindsym $mod+XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_volume

# Microphone control
set $refresh_microphone pkill -RTMIN+11 i3blocks
bindsym $mod+XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_microphone
bindsym $mod+XF86Launch5 exec --no-startup-id pactl set-source-volume @DEFAULT_SOURCE@ +5% && $refresh_microphone
bindsym $mod+XF86Launch6 exec --no-startup-id pactl set-source-volume @DEFAULT_SOURCE@ -5% && $refresh_microphone
