
# Change focus
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# Move focused window
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# Split in horizontal orientation
bindsym $mod+h split h

# Split in vertical orientation
bindsym $mod+v split v

# Enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# Change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# Toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# Change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# Sticky floating windows
# sticky enable|disable|toggle
bindsym $mod+t sticky toggle

# Focus the parent container
bindsym $mod+a focus parent

# Focus the child container
bindsym $mod+c focus child

# Focus on window activation
# focus_on_window_activation smart|urgent|focus|none
focus_on_window_activation focus

# Focus follows the mouse
# focus_follows_mouse yes|no
focus_follows_mouse no
# Makes the mouse follow the focus between screens
# mouse_warping output|none
mouse_warping output

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# Move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar