set $bg #000000
set $fg #C9D6DF
set $separator #666666


# workspace

set $border_color #2f343a

set $focused_color #c4c4c4
set $focused_text #000000

set $active_color #3a3a3a
set $active_text #d9d9d9

set $inactive_color #3a3a3a
set $inactive_text #d9d9d9

set $urgent_color #900000
set $urgent_text #d9d9d9

set $binding_color #900000
set $binding_text #d9d9d9