#!/bin/bash

STATE_FILE="/tmp/polybar-filesystem"

# alterna modo ao clicar
if [[ "$1" == "toggle" ]]; then
  if [[ -f "$STATE_FILE" ]]; then
    rm "$STATE_FILE"
  else
    touch "$STATE_FILE"
  fi
fi

MODE="compact"
[[ -f "$STATE_FILE" ]] && MODE="full"

root_pct=$(df / | awk 'NR==2 {print $5}')
home_pct=$(df /home | awk 'NR==2 {print $5}')

if [[ "$MODE" == "compact" ]]; then
  printf "/ %s HOME %s" $root_pct $home_pct
else
  root_full=$(df -h / | awk 'NR==2 {print $3 "/" $2}')
  home_full=$(df -h /home | awk 'NR==2 {print $3 "/" $2}')
  printf "/ %s %s HOME %s %s" $root_full $root_pct $home_full $home_pct
fi