#!/bin/bash

STATE_FILE="/tmp/polybar-filesystem"

PARTITIONS=(
  "/"
  "/home"
)

get_fs_info() {
  df -hP "$1" 2>/dev/null | awk 'NR==2 {print $3, $2, $5}'
}

# toggle mode by clicking
[[ "$1" == "toggle" ]] && ([[ -e "$STATE_FILE" ]] && rm "$STATE_FILE" || touch "$STATE_FILE")

expanded=false
[[ -e "$STATE_FILE" ]] && expanded=true

for partition in "${PARTITIONS[@]}"; do
  read -r used size percent <<< "$(get_fs_info "$partition")"

  LABEL="%{F#61afef}$partition%{F-}"

  if ! $expanded; then
    printf "%s %s " "$LABEL" "$percent"
  else
    printf "%s %s/%s " "$LABEL" "$used" "$size"
  fi
done
