#!/bin/bash

STATE_FILE="/tmp/polybar-memory"

# toggle mode by clicking
[[ "$1" == "toggle" ]] && (
    [[ -e "$STATE_FILE" ]] && rm "$STATE_FILE" || touch "$STATE_FILE"
    # força refresh seguro
    polybar-msg action "#memory.hook.0" >/dev/null 2>&1
    exit
)


mem=$(free | awk '/Mem:/ {printf "%.0f", $3/$2*100}')
swap=$(free | awk '/Swap:/ {if ($2 > 0) printf "%.0f", $3/$2*100; else print 0}')

ramp() {
    local p=$1
    if   [ "$p" -lt 13 ]; then echo ▁
    elif [ "$p" -lt 25 ]; then echo ▂
    elif [ "$p" -lt 38 ]; then echo ▃
    elif [ "$p" -lt 50 ]; then echo ▄
    elif [ "$p" -lt 63 ]; then echo ▅
    elif [ "$p" -lt 75 ]; then echo ▆
    elif [ "$p" -lt 88 ]; then echo ▇
    else echo █
    fi
}

if [ -e "$STATE_FILE" ]; then
    echo "RAM ${mem}% SWAP ${swap}%"
else
    echo "RAM $(ramp "$mem") SWAP $(ramp "$swap")"
fi