#!/bin/bash

source "$HOME/.config/i3blocks/scripts/utils/colors"

EXPAND_TIME=3

ramp() {
    local p=$1
    local c color

    if   [ "$p" -lt 5 ];  then c=" "
    elif [ "$p" -lt 13 ]; then c="▁"
    elif [ "$p" -lt 25 ]; then c="▂"
    elif [ "$p" -lt 38 ]; then c="▃"
    elif [ "$p" -lt 50 ]; then c="▄"
    elif [ "$p" -lt 63 ]; then c="▅"
    elif [ "$p" -lt 75 ]; then c="▆"
    elif [ "$p" -lt 88 ]; then c="▇"
    else c="█"
    fi

    if   [ "$p" -lt 60 ]; then color="$WARNING_BAR"
    elif [ "$p" -lt 80 ]; then color="$DANGER_BAR"
    else color="$PRIMARY_BAR"
    fi

    printf "<span bgcolor='%s' foreground='%s'>%s</span>" "$BACKGROUND_BAR" "$color" "$c"
    
}

# expandable_start() {
#     local state_file="$1"
#     local signal="$2"
#     local expand_time="${3:-${EXPAND_TIME:-10}}"

#     # If it is already expanded, any click collapses it.
#     if expandable "$state_file"; then
#         expandable_clear "$state_file"
#         return
#     fi

#     local pid=0 expires=0

#     expires=$(( $(date +%s) + expand_time ))

#     setsid bash -c "
#         sleep $expand_time
#         pkill -RTMIN+$signal i3blocks >/dev/null 2>&1
#     " >/dev/null 2>&1 &

#     echo "$! $expires" > "$state_file"
# }

# expandable_toggle() {
#     local state_file="$1"

#     # If it is already expanded, any click collapses it
#     if expandable "$state_file"; then
#         expandable_clear "$state_file"
#         return
#     fi

#     echo "-1 -1" > "$state_file"
# }

# expandable_clear() {
#     local state_file="$1"

#     if [[ -f "$state_file" ]]; then
#         local pid expires
#         read -r pid expires < "$state_file"

#         if (( pid > 0 )); then
#             kill "$pid" 2>/dev/null
#         fi

#         rm -f "$state_file"
#     fi
# }

# expandable() {
#     local state_file="$1"

#     [[ -f "$state_file" ]] || return 1

#     local pid expires
#     read -r pid expires < "$state_file"

#     (( expires == -1 )) && return 0

#     if (( $(date +%s) < expires )); then
#         return 0
#     fi

#     rm -f "$state_file"
#     return 1
# }