#!/bin/bash

source "$HOME/.config/i3blocks/scripts/utils/colors"

ramp() {
    local p="$1"
    local c color

    # Aceita inteiros e floats (42 -> 42, 42.7 -> 42)
    p=${p%%.*}

    # Caso o valor seja inválido, usa 0
    [[ $p =~ ^[0-9]+$ ]] || p=0

    if   (( p < 5 ));  then c=" "
    elif (( p < 13 )); then c="▁"
    elif (( p < 25 )); then c="▂"
    elif (( p < 38 )); then c="▃"
    elif (( p < 50 )); then c="▄"
    elif (( p < 63 )); then c="▅"
    elif (( p < 75 )); then c="▆"
    elif (( p < 88 )); then c="▇"
    else                    c="█"
    fi

    if   (( p < 75 )); then
        color="$WARNING_BAR"
    elif (( p < 80 )); then
        color="$DANGER_BAR"
    else
        color="$PRIMARY_BAR"
    fi

    printf "<span bgcolor='%s' foreground='%s'>%s</span>" \
        "$BACKGROUND_BAR" "$color" "$c"
}
