position = "top"
height = 24
popup_gap = 5
popup_autohide = false

include = ["power-menu.toml"]

[[start]]
type = "workspaces"

#############################
# Windows title
#############################
[[start]]
type = "focused"
icon_size = 16

[start.truncate]
mode = "middle"
max_length = 50

#############################
# Clock and calender
#############################
[[center]]
type = "clock"
format = "%d/%m %H:%M"
show_week_numbers = true

# [[end]]
# type = "script"
# cmd = "~/.config/ironbar/scripts/cpu.sh"
# interval = 1000
# mode = "poll"

# [[end]]
# type = "script"
# name = "network-bar"
# cmd = "bash ~/.config/ironbar/scripts/network.sh"
# mode = "watch"
# on_click_left = "bash ~/.config/ironbar/scripts/network.sh toggle"

# [[end]]
# type = "battery"
# show_if = "ls /sys/class/power_supply/ | grep --quiet '^BAT'"

#############################
# System informations
#############################
[[end]]
type = "sys_info"

format = ["CPU {cpu_percent}%", "MEM {memory_percent}%", "T {temp_c}°C"]

[end.interval]
cpu = 1
memory = 60

#############################
# Custom popup network
#############################
[[end]]
type = "label"
name = "network"
class = "network"

[[end.bar]]
type = "button"
label = "Network"
on_click = "popup:toggle"

[[end.popup]]
type = "box"
class = "popup-network"
orientation = "vertical"

[[end.popup.widgets]]
type = "script"
name = "interface"
cmd = "printf 'Interface: '; bash ~/.config/ironbar/scripts/network.sh interface"
mode = "watch"

[[end.popup.widgets]]
type = "script"
name = "ip"
cmd = "printf 'IP: '; bash ~/.config/ironbar/scripts/network.sh ip"
mode = "watch"

[[end.popup.widgets]]
type = "script"
name = "rate"
cmd = "bash ~/.config/ironbar/scripts/network.sh rate"
interval = 1000

#############################
# Tray
#############################
[[end]]
type = "tray"

#############################
# Power menu
#############################
[[end]]
type = "custom"
name = "power-menu"
class = "power-menu"

[[end.bar]]
type = "button"
name = "power-btn"
label = ""
on_click = "popup:toggle"

[[end.popup]]
type = "box"
orientation = "vertical"

[[end.popup.widgets]]
type = "button"
class = "power-btn"
label = "shutdown"
on_click = "!shutdown now"

[[end.popup.widgets]]
type = "button"
class = "power-btn"
label = "reboot"
on_click = "!reboot"
