[global/wm]
include-file = ~/.config/polybar/colors.ini

[bar/main]
monitor = DP-1
width = 100%
; height = 20px
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

; line-size = 10px

border-size = 1px
border-color = #00000000

padding-left = 0px
padding-right = 4px

module-margin = 4px

separator = |
separator-foreground = ${colors.separator}

font-0 = DejaVu Sans Mono:size=10
; font-0 = "JetBrainsMono Nerd Font:style=Regular:size=10;2"

modules-left = xworkspaces
; xwindow
modules-center = date
modules-right = filesystem pulseaudio xkeyboard memory cpu temperature network

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = right

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

override-redirect = false
; pin-workspaces = true

[bar/secondary]
inherit = bar/main
monitor = DP-2
; pin-workspaces = true

[module/xworkspaces]
type = internal/xworkspaces

pin-workspaces = true

label-active = %name%
label-active-background = ${colors.primary}
label-active-foreground = ${colors.background}
label-active-padding = 4px
label-active-margin = 1px

label-occupied = %name%
label-occupied-background = #3a3a3a
label-occupied-padding = 4px
label-occupied-margin = 1px

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 4px
label-urgent-margin = 1px

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 4px
label-empty-margin = 1px

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%


[module/filesystem]
type = custom/script
exec = ~/.config/polybar/scripts/filesystem
; tail = true
interval=1
click-left = ~/.config/polybar/scripts/filesystem toggle

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-foreground = ${colors.foreground}
format-volume = <label-volume>

label-volume = %percentage%%


format-muted-prefix = "VOL "
format-muted-prefix-foreground = #FF0000
label-muted = "Mute"
label-muted-foreground = #FF0000 
; label-muted-foreground =${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

; [module/memory]
; type = internal/memory
; interval = 1
; format-foreground = ${colors.primary}
; warn-percentage = 90
; format = RAM <ramp-used> 
; ; SWAP <ramp-swap-used>
; label =  %percentage_used%
; ; label =  %percentage_used%  %percentage_swap_used%%

; ramp-used-0 = ▁
; ramp-used-1 = ▂
; ramp-used-2 = ▃
; ramp-used-3 = ▄
; ramp-used-4 = ▅
; ramp-used-5 = ▆
; ramp-used-6 = ▇
; ramp-used-7 = █

[module/memory]
type = custom/script
exec = ~/.config/polybar/scripts/memory
tail = true
click-left = ~/.config/polybar/scripts/memory toggle

[module/cpu]
type = internal/cpu
interval = 5
format-prefix-foreground = ${colors.primary}
format = <label> <ramp-coreload>
label = CPU %percentage%%

ramp-coreload-spacing = 0
ramp-coreload-0 = ▁
ramp-coreload-1 = ▂
ramp-coreload-2 = ▃
ramp-coreload-3 = ▄
ramp-coreload-4 = ▅
ramp-coreload-5 = ▆
ramp-coreload-6 = ▇
ramp-coreload-7 = █

[module/temperature]
type = internal/temperature
interval = 1
thermal-zone = 0
zone-type = x86_pkg_temp
format-prefix= "T "
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
base-temperature = 20
warn-temperature = 60

; [network-base]
; type = internal/network
; interval = 5
; format-connected = <label-connected>
; format-disconnected = <label-disconnected>
; label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

; [module/wlan]
; inherit = network-base
; interface-type = wireless
; label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

; [module/network]
; type = custom/script
; exec = ~/.config/polybar/scripts/network
; interval = 1

; [module/eth]
; inherit = network-base
; interface-type = wired
; label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1
date = %d/%m %H:%M
date-alt =%d/%m/%Y %H:%M:%S
label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
